# Generated by Django 5.0.6 on 2024-07-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_experiences_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
