# Generated by Django 5.0.6 on 2024-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_permission_role_rolepermission_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ManyToManyField(to='users.permission'),
        ),
    ]
